import { queryTimeline, queryAnomalies, queryBenchmarkSeries } from "./db.js";
import { SWARM } from "./config.js";

/* Generate a self-contained HTML mission report for the operator to
 * print to PDF (Ctrl-P in any browser). Covers: per-craft summary,
 * recent anomalies, recent timeline events, and benchmark statistics. */
export function buildReport(): string {
  const generatedAt = new Date().toISOString();
  const sections = SWARM.map(c => {
    const anomalies = queryAnomalies({ craft: c.id, limit: 25 });
    const tl = queryTimeline({ craft: c.id, limit: 50 });
    const bench = queryBenchmarkSeries(c.id, 30);

    const avg = (arr: number[]) => arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;
    const benchAvg = {
      queue:  Math.round(avg(bench.map(b => b.queueUs))),
      mutex:  Math.round(avg(bench.map(b => b.mutexUs))),
      notify: Math.round(avg(bench.map(b => b.notifyUs))),
      ctx:    Math.round(avg(bench.map(b => b.ctxUs))),
      jitter: Math.round(avg(bench.map(b => b.jitterUs))),
      mem:    Math.round(avg(bench.map(b => b.memUs))),
    };

    return `
      <section class="craft">
        <h2>${c.id} · ${c.label} · ${c.orbit}</h2>

        <h3>Benchmark averages (μs)</h3>
        <table>
          <thead><tr><th>queue</th><th>mutex</th><th>notify</th><th>ctx</th><th>jitter</th><th>mem</th></tr></thead>
          <tbody><tr>
            <td>${benchAvg.queue}</td><td>${benchAvg.mutex}</td><td>${benchAvg.notify}</td>
            <td>${benchAvg.ctx}</td><td>${benchAvg.jitter}</td><td>${benchAvg.mem}</td>
          </tr></tbody>
        </table>

        <h3>Anomalies (${anomalies.length})</h3>
        ${ anomalies.length ? `<table>
          <thead><tr><th>metric</th><th>value</th><th>z</th><th>ewma</th><th>severity</th><th>predicted</th><th>observed</th></tr></thead>
          <tbody>${anomalies.map(a => `
            <tr><td>${a.metric}</td><td>${a.value.toFixed(2)}</td><td>${a.zscore.toFixed(2)}</td>
                <td>${a.ewma.toFixed(2)}</td><td class="sev-${a.severity}">${a.severity}</td>
                <td>${a.predicted ?? "—"}</td>
                <td>${new Date(a.observedAt).toISOString().substring(11,19)}</td></tr>`).join("")}</tbody>
        </table>` : `<p class="muted">No anomalies recorded.</p>` }

        <h3>Recent events (${tl.length})</h3>
        <ol class="events">
          ${tl.map(e => `<li class="ev-${e.kind}">
            <span class="ts">${new Date(e.receivedAt).toISOString().substring(11,19)}</span>
            <span class="kind">${e.kind}</span>
            <span>${escapeHtml(e.message)}</span>
          </li>`).join("")}
        </ol>
      </section>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>WatchCore Mission Report · ${generatedAt}</title>
<style>
  body{font:14px/1.5 ui-sans-serif,system-ui;color:#0f172a;background:#fff;margin:32px;max-width:1100px}
  h1{font-size:28px;border-bottom:2px solid #0f172a;padding-bottom:6px}
  h2{margin-top:32px;color:#0f172a;border-left:4px solid #5ac8fa;padding-left:10px}
  h3{margin-top:18px;color:#475569;font-size:13px;letter-spacing:1px;text-transform:uppercase}
  table{width:100%;border-collapse:collapse;font-family:ui-monospace,monospace;font-size:12px;margin:6px 0}
  th,td{border-bottom:1px solid #e2e8f0;padding:6px 8px;text-align:left}
  th{background:#f1f5f9;font-weight:600}
  .sev-high{color:#dc2626;font-weight:700}
  .sev-medium{color:#ea580c}
  .sev-low{color:#65a30d}
  .muted{color:#94a3b8;font-style:italic}
  .events{list-style:decimal;padding-left:22px;font-family:ui-monospace,monospace;font-size:11px}
  .events li{margin:2px 0}
  .events .ts{color:#64748b;margin-right:8px}
  .events .kind{display:inline-block;min-width:80px;color:#0f766e;font-weight:600}
  .ev-mode .kind{color:#7c3aed}
  .ev-fault .kind{color:#dc2626}
  .ev-recovery .kind{color:#059669}
  .ev-anomaly .kind{color:#ea580c}
  header{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #0f172a;padding-bottom:8px;margin-bottom:20px}
  header .meta{text-align:right;color:#64748b;font-family:ui-monospace,monospace;font-size:11px}
  @media print{ body{margin:8mm} }
</style></head><body>
<header>
  <div>
    <div style="font-size:11px;color:#64748b;letter-spacing:2px;text-transform:uppercase">WatchCore RTOS</div>
    <h1 style="margin:4px 0">Mission Operations Report</h1>
  </div>
  <div class="meta">
    Generated: ${generatedAt}<br>
    Swarm size: ${SWARM.length} spacecraft
  </div>
</header>
${sections}
<footer style="margin-top:40px;padding-top:10px;border-top:1px solid #e2e8f0;font-size:11px;color:#64748b;font-family:ui-monospace,monospace">
  Generated by WatchCore Orchestrator · this report is reproducible from the SQLite database in web/backend/watchcore.db
</footer>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;" }[c]!));
}
